<?php

namespace Kettasoft\Filterable\Commands;

use Illuminate\Console\Command;
use Kettasoft\Filterable\Filterable;
use Kettasoft\Filterable\Commands\Concerns\CommandHelpers;

/**
 * Command to inspect the configuration and structure of a specific Filterable class.
 * 
 * This command allows users to provide a Filterable class name or alias and
 * retrieves detailed information about its configuration, including allowed fields,
 * operators, and the underlying model. It can also optionally display the SQL
 * query generated by the filter.
 * 
 * @package Kettasoft\Filterable\Commands
 */
class InspectFilterCommand extends Command
{
    use CommandHelpers;

    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'filterable:inspect {filter : The Filterable class or name}';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Inspect the configuration and structure of a specific Filterable class.';

    /**
     * Execute the console command.
     *
     * @return mixed
     */
    public function handle()
    {
        $filterInput = $this->argument('filter');
        $filterClass = $this->resolveFilterClass($filterInput);

        if (!$filterClass || !class_exists($filterClass)) {
            $this->error("Filter class [$filterInput] not found.");
            return Command::FAILURE;
        }

        $instance = new $filterClass();

        if (!is_subclass_of($instance, Filterable::class)) {
            $this->error("$filterClass is not a subclass of Filterable.");
            return Command::FAILURE;
        }

        $this->info("🔍 Inspecting: $filterClass");
        $this->line('');

        $this->table(['Property', 'Value'], [
            ['Model', $this->getModel($instance)],
            ['Allowed Fields', $this->highlight(implode(', ', $instance->getAllowedFields() ?? []) ?: '-', 'yellow')],
            ['Allowed Operators', $this->highlight(implode(', ', $instance->getAllowedOperators() ?? []), 'yellow') ?: '-'],
            ['Provided Data', implode(', ', $this->getProvidedData($instance)) ?: '-'],
            ['Ignored Empty Value', $instance->hasIgnoredEmptyValues() ? $this->highlight('Yes', 'green') : $this->highlight('No', 'red')],
            ['Strict Mode', $instance->isStrict() ? $this->highlight('Yes', 'green') : $this->highlight('No', 'red')],
            ['Engine', $this->getEngine($instance) ?: '-'],
            ['Has Sanitizers', $instance->getSanitizerInstance()->count() ? $this->highlight('Yes', 'green') : $this->highlight('No', 'red')],
            ['Request Source', $instance->getRequestSource() ?: '-'],
            ['Request Key', $instance->getFilterKey() ?: '-'],
            ['Validation Roles', implode(', ', array_keys($instance->rules())) ?: '-'],
        ], 'box-double');

        return Command::SUCCESS;
    }
}
